; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

; Generated by VC++ for Common Language Runtime
.file "C:\hmPy\hmPy.src\hmPy\Release\.NETFramework,Version=v4.8.AssemblyAttributes.cpp"
